export CATALINA_OPTS="$CATALINA_OPTS -ea"
export CATALINA_OPTS="$CATALINA_OPTS -Xms2g"
export CATALINA_OPTS="$CATALINA_OPTS -Dspring.profiles.active=$PROFILE"
export CATALINA_OPTS="$CATALINA_OPTS -Daws.region=$REGION"